# Generated by Django 2.2 on 2020-03-31 21:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('attorney_app', '0001_initial'),
        ('audit_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaseAudit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_number', models.CharField(max_length=30)),
                ('case_date', models.DateField()),
                ('judge', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attorney', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='case_audits', to='attorney_app.Attorney')),
                ('audit_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='case_audits', to='audit_app.AuditType')),
            ],
        ),
        migrations.CreateModel(
            name='CaseAuditCriteria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField()),
                ('comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('audit_criteria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='case_audit_criteria', to='audit_app.AuditCriteria')),
                ('case_audit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='case_audit_criteria', to='case_audit_app.CaseAudit')),
            ],
        ),
    ]
